// src/views/Home.vue
<template>
  <div class="home">
    <div class="logo-wrap">
      <img class="main-logo" src="@/assets/logo.png" />
      <h2 class="main-name">ortieez</h2>
    </div>
    <div class="center-text">
      <div class="center-wrap">
        <h1 class="main-center">Hey,I am ortieez!</h1>
        <h3 class="second-center">Web Developer. Designer. Student.</h3>
      </div>
    </div>
    <!-- <Nav/> -->
  </div>
</template>

<script>
// import Nav from '@/components/Nav.vue'

export default {
  name: "Home",
  components: {
    // Nav
  },
};
</script>

<style scoped>
.logo-wrap {
  display: flex;
  align-items: center;
}

.main-logo {
  margin: 1rem 0 0 6rem;
  width: 6rem;
}
.main-name {
  margin-bottom: 3px;
}

.center-text {
  display: flex;
  justify-content: center;
  text-align: center;
}

.main-center {
  font-size: 40px;
  margin: 0;
  margin-top: 45%;
}

.second-center {
  margin: 10px 0 0 0;
  font-size: 20px;
}
</style>

// src/lib/routes/Home.svelte
<script>
    import Background from '../elements/Background.svelte';
</script>

<main>
    <div class="center">
        <div class="logo">
            <img src="src/assets/logo/Logo-Light.png" alt="logo">
        </div>
        <div class="text">
            <h1>student</h1>
            <h1 class="push">developer</h1>
        </div>
    </div>
    <Background />
</main>

<style>
    .logo,
    .text {
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        
    }

    .text {
        display: flex;
        flex-direction: column;
        mix-blend-mode: difference;
        font-size: 3vw;
    }

    .text h1 {
        color: #EBDBB2;
        margin: 0;
    }

    .logo img {
        width: 58.8805166846071vh;
        opacity: .75;
        
    }

    .push {
        padding-left: 5vw;
    }
</style>
